# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistics.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        
        MainWindow.setStyleSheet("""
            QMainWindow {
                background-color: #2C2F33;
            }
            QLabel {
                color: #FFFFFF;
                font-size: 16px;
                font-weight: bold;
            }
            QComboBox {
                background-color: #23272A;
                color: #FFFFFF;
                border-radius: 5px;
                padding: 5px;
                font-size: 14px;
            }
            QPushButton {
                background-color: #7289DA;
                color: white;
                border-radius: 8px;
                padding: 8px;
                font-size: 14px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #677BC4;
            }
            QTextEdit {
                background-color: #23272A;
                color: white;
                border: 2px solid #7289DA;
                border-radius: 5px;
                font-size: 14px;
            }
        """)


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(43, 53, 521, 491))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.widget)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.combo_statistics = QtWidgets.QComboBox(self.widget)
        self.combo_statistics.setObjectName("combo_statistics")
        self.combo_statistics.addItem("")
        self.combo_statistics.addItem("")
        self.combo_statistics.addItem("")
        self.verticalLayout.addWidget(self.combo_statistics)
        self.btn_generate = QtWidgets.QPushButton(self.widget)
        self.btn_generate.setObjectName("btn_generate")
        self.verticalLayout.addWidget(self.btn_generate)
        self.text_display = QtWidgets.QTextEdit(self.widget)
        self.text_display.setObjectName("text_display")
        self.verticalLayout.addWidget(self.text_display)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Select Statistics to Display:"))
        self.combo_statistics.setItemText(0, _translate("MainWindow", "Lahore Statistics"))
        self.combo_statistics.setItemText(1, _translate("MainWindow", "Peshawar Statistics"))
        self.combo_statistics.setItemText(2, _translate("MainWindow", "Combined Statistics"))
        self.btn_generate.setText(_translate("MainWindow", "Generate Statistics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
